// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WeatherSeasons
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("march_equinox")]
        public DateTimeOffset MarchEquinox { get; set; }

        [JsonProperty("june_solstice")]
        public DateTimeOffset JuneSolstice { get; set; }

        [JsonProperty("september_equinox")]
        public DateTimeOffset SeptemberEquinox { get; set; }

        [JsonProperty("december_solstice")]
        public DateTimeOffset DecemberSolstice { get; set; }
    }
}
